### ISSUE TITLE
xorshift as prng

### ISSUE THREAD

**Issue by fanatid** [crypto-browserify/pseudorandombytes#2]
@calvinmetcalf what you think about [xorshift](http://xorshift.di.unimi.it/) ([fanatid/xorshift.js](https://github.com/fanatid/xorshift.js)) instead chacha20poly1305?

**Comment by dcousens** [comment]
Since this is not intended to be cryptographically random.  ACK

**Comment by calvinmetcalf** [comment]
ok sell it to me
